"""init

Revision ID: 2b9c1df940ca
Revises: 
Create Date: 2025-08-07 07:49:07.106871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b9c1df940ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activity_types.activity_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activity_types_activity_id'), 'activity_types', ['activity_id'], unique=False)
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('point_x', sa.Float(), nullable=False),
    sa.Column('point_y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phones', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_table('organizations_activity_types',
    sa.Column('org_activity_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.activity_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('org_activity_id')
    )
    op.create_index(op.f('ix_organizations_activity_types_org_activity_id'), 'organizations_activity_types', ['org_activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_activity_types_org_activity_id'), table_name='organizations_activity_types')
    op.drop_table('organizations_activity_types')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_buildings_building_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_activity_types_activity_id'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
